name: Deploy branch

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install clojure CLI
        run: |
          sudo apt-get install -y rlwrap
          curl -L -O https://github.com/clojure/brew-install/releases/latest/download/linux-install.sh
          chmod +x linux-install.sh
          sudo ./linux-install.sh
      - name: Switch to master branch
        uses: actions/checkout@v4
        with:
          ref: master
          fetch-depth: 0
      - name: clean build files
        run: rm -rf public/js public/css/main-tw.css
      - name: Install npm deps
        run: npm i
      - name: Build release
        run: clj -M:shadow-cljs release portfolio
      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3 # or specific "vX.X.X" version tag for this action
        with:
          path: public/

  deploy:
    needs: build
    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
